% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={tp\_serie\_temporelle},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{tp\_serie\_temporelle}
\author{}
\date{\vspace{-2.5em}2025-10-02}

\begin{document}
\maketitle

\subsection{Contexte du TP}\label{contexte-du-tp}

\begin{verbatim}
## Registered S3 method overwritten by 'quantmod':
##   method            from
##   as.zoo.data.frame zoo
\end{verbatim}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{verbatim}
## Loading required package: parallel
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'forecast'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:Metrics':
## 
##     accuracy
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:FinTS':
## 
##     Acf
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'gridExtra'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     combine
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'psych'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:ggplot2':
## 
##     %+%, alpha
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 2
##   mois       T_moy
##   <date>     <dbl>
## 1 1990-01-01  2.46
## 2 1990-02-01 10   
## 3 1990-03-01  9.25
## 4 1990-04-01  9.65
## 5 1990-05-01 18.2 
## 6 1990-06-01 18.6
\end{verbatim}

Les données journalières de température à Lyon entre 1990 et 2025 ont
été importées avec succès et converties de °F en °C. Elles ont ensuite
été agrégées en moyennes mensuelles, donnant une série temporelle de
fréquence 12. La série montre une saisonnalité annuelle très nette, avec
des pics estivaux (≈ juillet--août) et des creux hivernaux (≈ janvier).
L'amplitude des variations saisonnières est d'environ 20°C, stable au
fil des années.

Le nombre totale de mois observé est 427 entre Janvier 1990 et Juillet
2025.

\begin{longtable}[]{@{}lr@{}}
\caption{Statistiques descriptives de la série
temporelle}\tabularnewline
\toprule\noalign{}
Statistique & Valeur \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Statistique & Valeur \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Moyenne & 13.175 \\
Médiane & 12.634 \\
Variance & 47.203 \\
Skewness (asymétrie) & 0.044 \\
Kurtosis (aplatissement) & 1.788 \\
\end{longtable}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-5-1.pdf}

La série temporelle présente une moyenne d'environ 13,2°C et une médiane
proche (12,6°C), ce qui suggère une distribution globalement symétrique.
La variance (47,2) indique une dispersion modérée des valeurs autour de
la moyenne, avec un écart-type d'environ 7°C. Le skewness proche de zéro
(0,04) confirme l'absence d'asymétrie marquée, tandis que le kurtosis
inférieur à 3 (1,79) traduit une distribution plus aplatie que la
normale, avec moins de valeurs extrêmes.

La série présente une forte saisonnalité annuelle (été chaud, hiver
froid), avec une amplitude assez stable (\textasciitilde20°C). On peut
suspecter une tendance légèrement haussière des températures maximales
récentes, mais ce n'est pas flagrant visuellement.

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-6-1.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-6-2.pdf}
La volatilité dépend du mois étudié. Sur le graphe on voit
l'hétéroscélasticité des températures, notament un écart type plus
important pour le mois de Janvier avec un écart type de 1.876471°C ou
Février avec 2.472963°c contre un écart type de température plus faible
pour les mois de Mars ou Avril (1.350898°C resp. 1.497665°C) par
exemple.

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{verbatim}
## 
## Test ADF après différenciation (d=1) :
\end{verbatim}

\begin{verbatim}
## p-value : 0.01
\end{verbatim}

La différentiationd'ordre 1 n'est pas satisfaisante. Regardons avec lag
12.

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-8-1.pdf}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  des_data
## Dickey-Fuller = -6.0214, Lag order = 7, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{verbatim}
## INTERPRÉTATION DU TEST ADF :
## -----------------------------
## - H0 : la série n'est pas Stationnaire
## - p-value < 0.05 → On REJETTE H0
## - ✓ La série est stationnaire.
\end{verbatim}

\begin{verbatim}
## 
## Test KPSS sur la série brute :
\end{verbatim}

\begin{verbatim}
## -------------------------------
\end{verbatim}

\begin{verbatim}
## Statistique KPSS : 0.0148
\end{verbatim}

\begin{verbatim}
## p-value : 0.1
\end{verbatim}

\begin{verbatim}
## ✓ La série est STATIONNAIRE (p ≥ 0.05)
\end{verbatim}

Deux tests statistiques ont été appliqués à la série désaisonnalisée :
Test ADF (Augmented Dickey-Fuller) :

Statistique = -6.02

p-value = 0.01 → On rejette l'hypothèse de non-stationnarité, la série
est donc stationnaire.

Test KPSS (Kwiatkowski-Phillips-Schmidt-Shin) :

Statistique = 0.0148

p-value = 0.1 → On ne rejette pas l'hypothèse de stationnarité. Les deux
tests aboutissent à la même conclusion : la série des\_data est
stationnaire après différenciation annuelle. Cela confirme que la
tendance et la saisonnalité ont été correctement supprimées, et que la
série est maintenant prête pour la modélisation ARIMA.

\begin{verbatim}
##    type ordre      AIC      BIC
## 1    AR     1 1927.719 1939.804
## 2    AR     2 1929.719 1945.832
## 3    AR     3 1927.366 1947.507
## 4    AR     4 1924.823 1948.993
## 5    AR     5 1925.133 1953.331
## 6    MA     1 1927.547 1939.632
## 7    MA     2 1929.420 1945.533
## 8    MA     3 1923.309 1943.450
## 9    MA     4 1921.099 1945.268
## 10   MA     5 1920.221 1948.419
\end{verbatim}

\begin{verbatim}
## Meilleur modèle selon AIC: MA ( 5 )
##  Meilleur modèle selon BIC: MA ( 1 )
##  Meilleur modèle AR selon AIC: AR ( 4 )
##  Meilleur modèle AR selon BIC: AR ( 1 )
##  Meilleur modèle MA selon AIC: MA ( 5 )
##  Meilleur modèle MA selon BIC: MA ( 1 )
\end{verbatim}

Effectivement, les modèles avec plus de paramètres ont un meilleur AIC
mais c'est dû à un ``sur-apprentissage'' qui est mis en évidence par la
mesure du BIC qui met les modèles AR(1) et MA(1) en avant. On comprend
bien intuitivement que la température moyenne pour le mois de juin par
exemple dépend peu de la température de la même année en Janvier.

\begin{verbatim}
## 
## Meilleur modèle ARMA selon AIC: ARMA( 5 0 5 )
##  Meilleur modèle ARMA selon BIC: ARMA( 5 0 5 )
\end{verbatim}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-13-1.pdf}
Analyse des résidus : Pour le modèle AR(4) :

L'ACF des résidus montre encore des pics significatifs →
autocorrélations résiduelles non négligeables.

Le test de Ljung--Box (p-value \textless{} 0.001) confirme la présence
d'autocorrélation → modèle insuffisant.

Pour le modèle ARMA(5,5) :

L'ACF des résidus est plus aléatoire, avec des valeurs globalement dans
les bandes de confiance.

Le test de Ljung--Box (p-value = 6.38×10⁻¹³) reste significatif, mais
indique une amélioration par rapport au modèle AR pur.

L'histogramme des résidus est centré sur 0, proche d'une distribution
normale.

Conclusion : Le modèle ARMA(5,5) améliore nettement l'ajustement par
rapport au modèle AR(4), mais c'est le modèle saisonnier ARMA(12,12)
restreint qui fournit les résidus les plus satisfaisants (non
autocorrélés et à moyenne nulle). Il constitue donc le meilleur modèle
pour la série désaisonnalisée.

Partie 2 : Modélisation et analyse

\begin{verbatim}
## [1] 1924.823
\end{verbatim}

\begin{verbatim}
## [1] 1844.665
\end{verbatim}

Les résidus ne peuvent pas être considéré comme des bruits blancs au vu
du test de Ljung-Box avec des p\_value égal à des 0 machine. On le voit
avec le plot des ACF des 2 modèles qui montrent une corrélation au lag
12 (Le mois de l'année précedente).
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-15-1.pdf}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_AR
## X-squared = 120.67, df = 12, p-value < 2.2e-16
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_ARMA
## X-squared = 72.822, df = 12, p-value = 9.463e-11
\end{verbatim}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-15-2.pdf}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_subsetAR_12
## X-squared = 41.747, df = 12, p-value = 3.673e-05
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_subsetAR_36
## X-squared = 36.894, df = 12, p-value = 0.0002324
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_subsetAR_36
## X-squared = 109.36, df = 25, p-value = 1.588e-12
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_subsetARMA
## X-squared = 13.728, df = 12, p-value = 0.3184
\end{verbatim}

\begin{verbatim}
## [1] 415
\end{verbatim}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-16-2.pdf}

\subsection{Test de Ljung--Box}\label{test-de-ljungbox}

La statistique du test est donnée par :

\[
Q = n (n + 2) \sum_{k=1}^{m} \frac{\hat{\rho}(k)^2}{n - k}
\]

Sous l'hypothèse nulle \(H_0\) d'absence d'autocorrélation,\\
on a :

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-20-1.pdf}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-21-1.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-21-2.pdf}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_AR_1
## X-squared = 129.55, df = 12, p-value < 2.2e-16
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  res_MA_1
## X-squared = 130.88, df = 12, p-value < 2.2e-16
\end{verbatim}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-23-2.pdf}

\begin{verbatim}
## Sélection automatique du meilleur modèle ARIMA...
\end{verbatim}

\begin{verbatim}
## 
##  ARIMA(0,0,0)            with zero mean     : 1936.831
##  ARIMA(0,0,0)            with non-zero mean : 1938.797
##  ARIMA(0,0,0)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,0)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,0)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,0)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,0)(1,0,0)[12] with zero mean     : 1813.257
##  ARIMA(0,0,0)(1,0,0)[12] with non-zero mean : 1814.972
##  ARIMA(0,0,0)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,0)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,0)(1,0,2)[12] with zero mean     : 1684.991
##  ARIMA(0,0,0)(1,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,0)(2,0,0)[12] with zero mean     : 1748.268
##  ARIMA(0,0,0)(2,0,0)[12] with non-zero mean : 1749.461
##  ARIMA(0,0,0)(2,0,1)[12] with zero mean     : 1684.581
##  ARIMA(0,0,0)(2,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,0)(2,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,0)(2,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,1)            with zero mean     : 1925.618
##  ARIMA(0,0,1)            with non-zero mean : 1927.606
##  ARIMA(0,0,1)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,1)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,1)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,1)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,1)(1,0,0)[12] with zero mean     : 1800.929
##  ARIMA(0,0,1)(1,0,0)[12] with non-zero mean : 1802.737
##  ARIMA(0,0,1)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,1)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,1)(1,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,1)(1,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,1)(2,0,0)[12] with zero mean     : 1741.586
##  ARIMA(0,0,1)(2,0,0)[12] with non-zero mean : 1742.995
##  ARIMA(0,0,1)(2,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,1)(2,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,1)(2,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,1)(2,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,2)            with zero mean     : 1927.522
##  ARIMA(0,0,2)            with non-zero mean : 1929.518
##  ARIMA(0,0,2)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,2)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,2)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,2)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,2)(1,0,0)[12] with zero mean     : 1802.965
##  ARIMA(0,0,2)(1,0,0)[12] with non-zero mean : 1804.784
##  ARIMA(0,0,2)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,2)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,2)(1,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,2)(1,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,2)(2,0,0)[12] with zero mean     : 1742.918
##  ARIMA(0,0,2)(2,0,0)[12] with non-zero mean : 1744.278
##  ARIMA(0,0,2)(2,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,2)(2,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,3)            with zero mean     : 1921.438
##  ARIMA(0,0,3)            with non-zero mean : 1923.455
##  ARIMA(0,0,3)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,3)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,3)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(0,0,3)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(0,0,3)(1,0,0)[12] with zero mean     : 1796.602
##  ARIMA(0,0,3)(1,0,0)[12] with non-zero mean : 1798.498
##  ARIMA(0,0,3)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,3)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,3)(2,0,0)[12] with zero mean     : 1738.244
##  ARIMA(0,0,3)(2,0,0)[12] with non-zero mean : 1739.801
##  ARIMA(0,0,4)            with zero mean     : 1919.282
##  ARIMA(0,0,4)            with non-zero mean : 1921.305
##  ARIMA(0,0,4)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(0,0,4)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(0,0,4)(1,0,0)[12] with zero mean     : 1797.858
##  ARIMA(0,0,4)(1,0,0)[12] with non-zero mean : 1799.748
##  ARIMA(0,0,5)            with zero mean     : 1918.458
##  ARIMA(0,0,5)            with non-zero mean : 1920.496
##  ARIMA(1,0,0)            with zero mean     : 1925.786
##  ARIMA(1,0,0)            with non-zero mean : 1927.777
##  ARIMA(1,0,0)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,0)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,0)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(1,0,0)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(1,0,0)(1,0,0)[12] with zero mean     : 1800.621
##  ARIMA(1,0,0)(1,0,0)[12] with non-zero mean : 1802.447
##  ARIMA(1,0,0)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,0)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,0)(1,0,2)[12] with zero mean     : Inf
##  ARIMA(1,0,0)(1,0,2)[12] with non-zero mean : Inf
##  ARIMA(1,0,0)(2,0,0)[12] with zero mean     : 1742.131
##  ARIMA(1,0,0)(2,0,0)[12] with non-zero mean : 1743.557
##  ARIMA(1,0,0)(2,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,0)(2,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,0)(2,0,2)[12] with zero mean     : Inf
##  ARIMA(1,0,0)(2,0,2)[12] with non-zero mean : Inf
##  ARIMA(1,0,1)            with zero mean     : 1907.459
##  ARIMA(1,0,1)            with non-zero mean : 1909.453
##  ARIMA(1,0,1)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,1)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,1)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(1,0,1)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(1,0,1)(1,0,0)[12] with zero mean     : 1801.971
##  ARIMA(1,0,1)(1,0,0)[12] with non-zero mean : 1803.844
##  ARIMA(1,0,1)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,1)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,1)(1,0,2)[12] with zero mean     : Inf
##  ARIMA(1,0,1)(1,0,2)[12] with non-zero mean : Inf
##  ARIMA(1,0,1)(2,0,0)[12] with zero mean     : 1738.837
##  ARIMA(1,0,1)(2,0,0)[12] with non-zero mean : 1740.175
##  ARIMA(1,0,1)(2,0,1)[12] with zero mean     : 1674.666
##  ARIMA(1,0,1)(2,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,2)            with zero mean     : Inf
##  ARIMA(1,0,2)            with non-zero mean : Inf
##  ARIMA(1,0,2)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,2)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,2)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(1,0,2)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(1,0,2)(1,0,0)[12] with zero mean     : 1803.328
##  ARIMA(1,0,2)(1,0,0)[12] with non-zero mean : 1805.216
##  ARIMA(1,0,2)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,2)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,2)(2,0,0)[12] with zero mean     : 1740.52
##  ARIMA(1,0,2)(2,0,0)[12] with non-zero mean : 1741.908
##  ARIMA(1,0,3)            with zero mean     : 1905.763
##  ARIMA(1,0,3)            with non-zero mean : 1907.79
##  ARIMA(1,0,3)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(1,0,3)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(1,0,3)(1,0,0)[12] with zero mean     : 1795.911
##  ARIMA(1,0,3)(1,0,0)[12] with non-zero mean : 1797.793
##  ARIMA(1,0,4)            with zero mean     : Inf
##  ARIMA(1,0,4)            with non-zero mean : Inf
##  ARIMA(2,0,0)            with zero mean     : 1927.816
##  ARIMA(2,0,0)            with non-zero mean : 1929.816
##  ARIMA(2,0,0)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(2,0,0)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(2,0,0)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(2,0,0)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(2,0,0)(1,0,0)[12] with zero mean     : 1802.543
##  ARIMA(2,0,0)(1,0,0)[12] with non-zero mean : 1804.387
##  ARIMA(2,0,0)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(2,0,0)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(2,0,0)(1,0,2)[12] with zero mean     : Inf
##  ARIMA(2,0,0)(1,0,2)[12] with non-zero mean : Inf
##  ARIMA(2,0,0)(2,0,0)[12] with zero mean     : 1743.955
##  ARIMA(2,0,0)(2,0,0)[12] with non-zero mean : 1745.351
##  ARIMA(2,0,0)(2,0,1)[12] with zero mean     : Inf
##  ARIMA(2,0,0)(2,0,1)[12] with non-zero mean : Inf
##  ARIMA(2,0,1)            with zero mean     : Inf
##  ARIMA(2,0,1)            with non-zero mean : Inf
##  ARIMA(2,0,1)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(2,0,1)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(2,0,1)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(2,0,1)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(2,0,1)(1,0,0)[12] with zero mean     : 1803.609
##  ARIMA(2,0,1)(1,0,0)[12] with non-zero mean : 1805.498
##  ARIMA(2,0,1)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(2,0,1)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(2,0,1)(2,0,0)[12] with zero mean     : Inf
##  ARIMA(2,0,1)(2,0,0)[12] with non-zero mean : Inf
##  ARIMA(2,0,2)            with zero mean     : Inf
##  ARIMA(2,0,2)            with non-zero mean : Inf
##  ARIMA(2,0,2)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(2,0,2)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(2,0,2)(1,0,0)[12] with zero mean     : 1793.479
##  ARIMA(2,0,2)(1,0,0)[12] with non-zero mean : 1795.395
##  ARIMA(2,0,3)            with zero mean     : 1907.352
##  ARIMA(2,0,3)            with non-zero mean : 1909.392
##  ARIMA(3,0,0)            with zero mean     : 1925.494
##  ARIMA(3,0,0)            with non-zero mean : 1927.512
##  ARIMA(3,0,0)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(3,0,0)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(3,0,0)(0,0,2)[12] with zero mean     : Inf
##  ARIMA(3,0,0)(0,0,2)[12] with non-zero mean : Inf
##  ARIMA(3,0,0)(1,0,0)[12] with zero mean     : 1799.407
##  ARIMA(3,0,0)(1,0,0)[12] with non-zero mean : 1801.31
##  ARIMA(3,0,0)(1,0,1)[12] with zero mean     : Inf
##  ARIMA(3,0,0)(1,0,1)[12] with non-zero mean : Inf
##  ARIMA(3,0,0)(2,0,0)[12] with zero mean     : 1740.212
##  ARIMA(3,0,0)(2,0,0)[12] with non-zero mean : 1741.781
##  ARIMA(3,0,1)            with zero mean     : 1905.6
##  ARIMA(3,0,1)            with non-zero mean : 1907.628
##  ARIMA(3,0,1)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(3,0,1)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(3,0,1)(1,0,0)[12] with zero mean     : 1794.407
##  ARIMA(3,0,1)(1,0,0)[12] with non-zero mean : 1796.299
##  ARIMA(3,0,2)            with zero mean     : 1907.479
##  ARIMA(3,0,2)            with non-zero mean : 1909.52
##  ARIMA(4,0,0)            with zero mean     : 1923.008
##  ARIMA(4,0,0)            with non-zero mean : 1925.029
##  ARIMA(4,0,0)(0,0,1)[12] with zero mean     : Inf
##  ARIMA(4,0,0)(0,0,1)[12] with non-zero mean : Inf
##  ARIMA(4,0,0)(1,0,0)[12] with zero mean     : 1799.596
##  ARIMA(4,0,0)(1,0,0)[12] with non-zero mean : 1801.487
##  ARIMA(4,0,1)            with zero mean     : 1907.284
##  ARIMA(4,0,1)            with non-zero mean : 1909.325
##  ARIMA(5,0,0)            with zero mean     : 1923.37
##  ARIMA(5,0,0)            with non-zero mean : 1925.408
## 
## 
## 
##  Best model: ARIMA(1,0,1)(2,0,1)[12] with zero mean
\end{verbatim}

\begin{verbatim}
## 
## ========================================
\end{verbatim}

\begin{verbatim}
## MEILLEUR MODÈLE SÉLECTIONNÉ
\end{verbatim}

\begin{verbatim}
## ========================================
\end{verbatim}

\begin{verbatim}
## Series: des_data 
## ARIMA(1,0,1)(2,0,1)[12] with zero mean 
## 
## Coefficients:
##           ar1     ma1     sar1     sar2     sma1
##       -0.5596  0.7149  -0.0828  -0.0461  -0.8856
## s.e.   0.1554  0.1313   0.0615   0.0585   0.0441
## 
## sigma^2 = 3.093:  log likelihood = -831.23
## AIC=1674.46   AICc=1674.67   BIC=1698.63
## 
## Training set error measures:
##                     ME     RMSE      MAE MPE MAPE      MASE       ACF1
## Training set 0.1965763 1.748182 1.428169 Inf  Inf 0.4074517 0.01816156
\end{verbatim}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}@{}}
\caption{Comparaison des Modèles ARIMA}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Modèle
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AIC
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
BIC
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AICc
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
LogLik
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Modèle
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AIC
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
BIC
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AICc
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
LogLik
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & Auto ARIMA & 1674.46 & 1698.63 & 1674.67 & -831.23 \\
ARIMA(2,0,2)(2,0,0){[}12{]} & ARIMA(2,0,2)(2,0,0){[}12{]} & 1742.40 &
1774.62 & 1742.75 & -863.20 \\
ARIMA(1,1,2)(2,1,1){[}12{]} & ARIMA(1,1,2)(2,1,1){[}12{]} & 1762.22 &
1790.22 & 1762.51 & -874.11 \\
ARIMA(2,1,2)(1,1,1){[}12{]} & ARIMA(2,1,2)(1,1,1){[}12{]} & 1808.50 &
1836.49 & 1808.79 & -897.25 \\
ARIMA(1,1,1)(1,1,1){[}12{]} & ARIMA(1,1,1)(1,1,1){[}12{]} & 1815.60 &
1835.59 & 1815.75 & -902.80 \\
\end{longtable}

\begin{verbatim}
## 
## ✓ Le meilleur modèle selon AICc est : Auto ARIMA
\end{verbatim}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,1)(2,0,1)[12] with zero mean
## Q* = 27.791, df = 19, p-value = 0.08753
## 
## Model df: 5.   Total lags used: 24
\end{verbatim}

\begin{verbatim}
## Test de Ljung-Box (H0 : pas d'autocorrélation) :
\end{verbatim}

\begin{verbatim}
##   p-value = 0.1907
\end{verbatim}

\begin{verbatim}
##   ✓ Les résidus sont un bruit blanc (p > 0.05)
\end{verbatim}

\begin{verbatim}
## Test de Shapiro-Wilk (H0 : normalité) :
\end{verbatim}

\begin{verbatim}
##   p-value = 0.3045
\end{verbatim}

\begin{verbatim}
##   ✓ Les résidus suivent une loi normale (p > 0.05)
\end{verbatim}

Les modèles qui ont passé la test de Box-Ljung sont les modèles
ARIMA(1,0,1)(2,0,1){[}12{]}, ARMA(12,0,12) subset \{AR:1,12 ; MA:12\}
équivalent à ARIMA(1,0,0)(1,0,1){[}12{]}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Analyse des résidus
  \includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-27-1.pdf}
\end{enumerate}

\subsection{Modèles ARCH et GARCH}\label{moduxe8les-arch-et-garch}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Test Arche Engle
\end{enumerate}

\begin{verbatim}
## 
##  ARCH LM-test; Null hypothesis: no ARCH effects
## 
## data:  residus
## Chi-squared = 15.49, df = 12, p-value = 0.2157
\end{verbatim}

\begin{verbatim}
## 
##  ARCH LM-test; Null hypothesis: no ARCH effects
## 
## data:  res_subsetARMA
## Chi-squared = 10.596, df = 12, p-value = 0.5638
\end{verbatim}

Le test ARCH d'Engle appliqué aux résidus de
l'ARIMA(1,0,0)(1,0,1){[}12{]} (p-value = 0,216) et de l'ARMA(12,0,12)
subset\{AR:1,2 ; MA:12\} (p-value \textgreater{} 0,05) n'est pas
significatif. Nous ne mettons donc pas en évidence d'hétéroscédastiscité
conditionnelle. Conformément aux consignes, nous estimons tout de même
un ARCH(1) puis un GARCH(1,1).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  Modèle ARCH(1) \& GARCH(1,1)
\item
  Critères AIC \& BIC
\end{enumerate}

\begin{verbatim}
## 
## *---------------------------------*
## *          GARCH Model Fit        *
## *---------------------------------*
## 
## Conditional Variance Dynamics    
## -----------------------------------
## GARCH Model  : sGARCH(1,0)
## Mean Model   : ARFIMA(12,0,12)
## Distribution : norm 
## 
## Optimal Parameters
## ------------------------------------
##         Estimate  Std. Error   t value Pr(>|t|)
## mu      0.029913    0.021986   1.36054 0.173660
## ar1     0.170133    0.050663   3.35816 0.000785
## ar2     0.000000          NA        NA       NA
## ar3     0.000000          NA        NA       NA
## ar4     0.000000          NA        NA       NA
## ar5     0.000000          NA        NA       NA
## ar6     0.000000          NA        NA       NA
## ar7     0.000000          NA        NA       NA
## ar8     0.000000          NA        NA       NA
## ar9     0.000000          NA        NA       NA
## ar10    0.000000          NA        NA       NA
## ar11    0.000000          NA        NA       NA
## ar12   -0.051428    0.057577  -0.89320 0.371748
## ma1     0.000000          NA        NA       NA
## ma2     0.000000          NA        NA       NA
## ma3     0.000000          NA        NA       NA
## ma4     0.000000          NA        NA       NA
## ma5     0.000000          NA        NA       NA
## ma6     0.000000          NA        NA       NA
## ma7     0.000000          NA        NA       NA
## ma8     0.000000          NA        NA       NA
## ma9     0.000000          NA        NA       NA
## ma10    0.000000          NA        NA       NA
## ma11    0.000000          NA        NA       NA
## ma12   -0.807436    0.033101 -24.39322 0.000000
## omega   3.201441    0.290469  11.02164 0.000000
## alpha1  0.028234    0.058809   0.48009 0.631160
## 
## Robust Standard Errors:
##         Estimate  Std. Error   t value Pr(>|t|)
## mu      0.029913    0.021996   1.35991 0.173859
## ar1     0.170133    0.055172   3.08371 0.002044
## ar2     0.000000          NA        NA       NA
## ar3     0.000000          NA        NA       NA
## ar4     0.000000          NA        NA       NA
## ar5     0.000000          NA        NA       NA
## ar6     0.000000          NA        NA       NA
## ar7     0.000000          NA        NA       NA
## ar8     0.000000          NA        NA       NA
## ar9     0.000000          NA        NA       NA
## ar10    0.000000          NA        NA       NA
## ar11    0.000000          NA        NA       NA
## ar12   -0.051428    0.062502  -0.82283 0.410607
## ma1     0.000000          NA        NA       NA
## ma2     0.000000          NA        NA       NA
## ma3     0.000000          NA        NA       NA
## ma4     0.000000          NA        NA       NA
## ma5     0.000000          NA        NA       NA
## ma6     0.000000          NA        NA       NA
## ma7     0.000000          NA        NA       NA
## ma8     0.000000          NA        NA       NA
## ma9     0.000000          NA        NA       NA
## ma10    0.000000          NA        NA       NA
## ma11    0.000000          NA        NA       NA
## ma12   -0.807436    0.033429 -24.15341 0.000000
## omega   3.201441    0.295696  10.82681 0.000000
## alpha1  0.028234    0.061768   0.45709 0.647604
## 
## LogLikelihood : -844.296 
## 
## Information Criteria
## ------------------------------------
##                    
## Akaike       4.0978
## Bayes        4.1561
## Shibata      4.0974
## Hannan-Quinn 4.1208
## 
## Weighted Ljung-Box Test on Standardized Residuals
## ------------------------------------
##                           statistic   p-value
## Lag[1]                        0.114 0.7356245
## Lag[2*(p+q)+(p+q)-1][71]     55.755 0.0000000
## Lag[4*(p+q)+(p+q)-1][119]    80.522 0.0004923
## d.o.f=24
## H0 : No serial correlation
## 
## Weighted Ljung-Box Test on Standardized Squared Residuals
## ------------------------------------
##                         statistic p-value
## Lag[1]                     0.2387  0.6251
## Lag[2*(p+q)+(p+q)-1][2]    2.6197  0.1780
## Lag[4*(p+q)+(p+q)-1][5]    4.1690  0.2337
## d.o.f=1
## 
## Weighted ARCH LM Tests
## ------------------------------------
##             Statistic Shape Scale P-Value
## ARCH Lag[2]     4.716 0.500 2.000 0.02988
## ARCH Lag[4]     4.821 1.397 1.611 0.09728
## ARCH Lag[6]     5.101 2.222 1.500 0.18408
## 
## Nyblom stability test
## ------------------------------------
## Joint Statistic:  1.4385
## Individual Statistics:              
## mu     0.20033
## ar1    0.05642
## ar12   0.64485
## ma12   0.73596
## omega  0.44592
## alpha1 0.09939
## 
## Asymptotic Critical Values (10% 5% 1%)
## Joint Statistic:          1.49 1.68 2.12
## Individual Statistic:     0.35 0.47 0.75
## 
## Sign Bias Test
## ------------------------------------
##                    t-value   prob sig
## Sign Bias           0.1765 0.8600    
## Negative Sign Bias  0.2865 0.7746    
## Positive Sign Bias  0.1358 0.8920    
## Joint Effect        0.5920 0.8983    
## 
## 
## Adjusted Pearson Goodness-of-Fit Test:
## ------------------------------------
##   group statistic p-value(g-1)
## 1    20     21.10       0.3315
## 2    30     37.46       0.1349
## 3    40     46.98       0.1782
## 4    50     50.66       0.4078
## 
## 
## Elapsed time : 0.2660298
\end{verbatim}

\begin{verbatim}
## 
## *---------------------------------*
## *          GARCH Model Fit        *
## *---------------------------------*
## 
## Conditional Variance Dynamics    
## -----------------------------------
## GARCH Model  : sGARCH(1,1)
## Mean Model   : ARFIMA(12,0,12)
## Distribution : norm 
## 
## Optimal Parameters
## ------------------------------------
##         Estimate  Std. Error     t value Pr(>|t|)
## mu      0.031747    0.021064  1.5072e+00  0.13177
## ar1     0.170268    0.049486  3.4407e+00  0.00058
## ar2     0.000000          NA          NA       NA
## ar3     0.000000          NA          NA       NA
## ar4     0.000000          NA          NA       NA
## ar5     0.000000          NA          NA       NA
## ar6     0.000000          NA          NA       NA
## ar7     0.000000          NA          NA       NA
## ar8     0.000000          NA          NA       NA
## ar9     0.000000          NA          NA       NA
## ar10    0.000000          NA          NA       NA
## ar11    0.000000          NA          NA       NA
## ar12   -0.059221    0.057487 -1.0302e+00  0.30293
## ma1     0.000000          NA          NA       NA
## ma2     0.000000          NA          NA       NA
## ma3     0.000000          NA          NA       NA
## ma4     0.000000          NA          NA       NA
## ma5     0.000000          NA          NA       NA
## ma6     0.000000          NA          NA       NA
## ma7     0.000000          NA          NA       NA
## ma8     0.000000          NA          NA       NA
## ma9     0.000000          NA          NA       NA
## ma10    0.000000          NA          NA       NA
## ma11    0.000000          NA          NA       NA
## ma12   -0.812430    0.032282 -2.5167e+01  0.00000
## omega   0.001429    0.007471  1.9134e-01  0.84826
## alpha1  0.000000    0.002429  1.0000e-06  1.00000
## beta1   0.999000    0.000029  3.4203e+04  0.00000
## 
## Robust Standard Errors:
##         Estimate  Std. Error     t value Pr(>|t|)
## mu      0.031747    0.022355  1.4202e+00 0.155564
## ar1     0.170268    0.056678  3.0041e+00 0.002664
## ar2     0.000000          NA          NA       NA
## ar3     0.000000          NA          NA       NA
## ar4     0.000000          NA          NA       NA
## ar5     0.000000          NA          NA       NA
## ar6     0.000000          NA          NA       NA
## ar7     0.000000          NA          NA       NA
## ar8     0.000000          NA          NA       NA
## ar9     0.000000          NA          NA       NA
## ar10    0.000000          NA          NA       NA
## ar11    0.000000          NA          NA       NA
## ar12   -0.059221    0.065766 -9.0048e-01 0.367867
## ma1     0.000000          NA          NA       NA
## ma2     0.000000          NA          NA       NA
## ma3     0.000000          NA          NA       NA
## ma4     0.000000          NA          NA       NA
## ma5     0.000000          NA          NA       NA
## ma6     0.000000          NA          NA       NA
## ma7     0.000000          NA          NA       NA
## ma8     0.000000          NA          NA       NA
## ma9     0.000000          NA          NA       NA
## ma10    0.000000          NA          NA       NA
## ma11    0.000000          NA          NA       NA
## ma12   -0.812430    0.034453 -2.3581e+01 0.000000
## omega   0.001429    0.005708  2.5045e-01 0.802243
## alpha1  0.000000    0.001905  1.0000e-06 0.999999
## beta1   0.999000    0.000030  3.3296e+04 0.000000
## 
## LogLikelihood : -843.165 
## 
## Information Criteria
## ------------------------------------
##                    
## Akaike       4.0972
## Bayes        4.1651
## Shibata      4.0966
## Hannan-Quinn 4.1240
## 
## Weighted Ljung-Box Test on Standardized Residuals
## ------------------------------------
##                           statistic  p-value
## Lag[1]                       0.1088 0.741494
## Lag[2*(p+q)+(p+q)-1][71]    54.3563 0.000000
## Lag[4*(p+q)+(p+q)-1][119]   78.5224 0.001338
## d.o.f=24
## H0 : No serial correlation
## 
## Weighted Ljung-Box Test on Standardized Squared Residuals
## ------------------------------------
##                         statistic p-value
## Lag[1]                    0.01284  0.9098
## Lag[2*(p+q)+(p+q)-1][5]   3.10673  0.3879
## Lag[4*(p+q)+(p+q)-1][9]   3.91069  0.6040
## d.o.f=2
## 
## Weighted ARCH LM Tests
## ------------------------------------
##             Statistic Shape Scale P-Value
## ARCH Lag[3]   0.02665 0.500 2.000  0.8703
## ARCH Lag[5]   0.16786 1.440 1.667  0.9729
## ARCH Lag[7]   0.60777 2.315 1.543  0.9676
## 
## Nyblom stability test
## ------------------------------------
## Joint Statistic:  2.2535
## Individual Statistics:              
## mu     0.20459
## ar1    0.04253
## ar12   0.63873
## ma12   0.76451
## omega  0.21870
## alpha1 0.20545
## beta1  0.22577
## 
## Asymptotic Critical Values (10% 5% 1%)
## Joint Statistic:          1.69 1.9 2.35
## Individual Statistic:     0.35 0.47 0.75
## 
## Sign Bias Test
## ------------------------------------
##                    t-value   prob sig
## Sign Bias          0.24979 0.8029    
## Negative Sign Bias 0.01613 0.9871    
## Positive Sign Bias 0.27026 0.7871    
## Joint Effect       0.48587 0.9220    
## 
## 
## Adjusted Pearson Goodness-of-Fit Test:
## ------------------------------------
##   group statistic p-value(g-1)
## 1    20     15.99       0.6581
## 2    30     30.08       0.4098
## 3    40     29.63       0.8607
## 4    50     48.98       0.4741
## 
## 
## Elapsed time : 0.1627581
\end{verbatim}

\begin{verbatim}
##                      
## Akaike       4.097812
## Bayes        4.156052
## Shibata      4.097402
## Hannan-Quinn 4.120842
\end{verbatim}

\begin{verbatim}
##                      
## Akaike       4.097181
## Bayes        4.165128
## Shibata      4.096624
## Hannan-Quinn 4.124049
\end{verbatim}

La comparaison des critères montre des écarts très faibles entre les
deux modèles. L'AIC est légèrement plus bas pour le GARCH(1,1),
suggérant un gain assez minime. En revanche le BIC est légèrement plus
bas pour le ARCH(1), ce qui suggère que le modèle ARCH(1) est moins
complexe. Ces deux critères ne reflètent pas un avantage d'un modèle par
rapport à l'autre.

On remarque que a dispersion des températures s'avérant systématiquement
plus élevée en hiver qu'en été. Nous pouvons donc retenir un modèle à
variance saisonnière attribuant un écart-type par mois, ce qui évite
d'alourdir le modèle avec un GARCH.
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-31-1.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-31-2.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-31-3.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-31-4.pdf}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  z_subsetARMA_GARCH
## X-squared = 29.557, df = 20, p-value = 0.07735
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  z_subsetARMA_GARCH^2
## X-squared = 18.482, df = 20, p-value = 0.5557
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  z_subsetARMA_ARCH
## X-squared = 30.776, df = 20, p-value = 0.05822
\end{verbatim}

\begin{verbatim}
## 
##  Box-Ljung test
## 
## data:  z_subsetARMA_ARCH^2
## X-squared = 19.84, df = 20, p-value = 0.468
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Résidus finaux
\end{enumerate}

Pour les deux modèles les test des résidus ne sont pas signifiactifs ,
ce qui suggère une autocorrélation résiduelle légère. En revanche, pour
les deux modèles, Box-Ljung indique l'abscence d'hétéroscédasticité
résiduelle sur les résidus au carré. De plus, les ACF restent
globalement dans les bandes de confiance avec quelques pics isolés vers
les lag 12 et 24, ce qui est cohérent avec la saisonnalité. Cependant,
il n'y a aucun motif systématique. Ce qui confirme que la moyenne est
bien spécifiée et que la variance résiduelle ne présente plus de
structure marquée.

Ainsi, nous priviligions au vu de ces résultats le modèle le moins
complexe : ARMA(12,0,12) subset \{AR:1,12 ; MA:12\} - ARCH(1)

\subsection{Prévision}\label{pruxe9vision}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-32-1.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-32-2.pdf}

\begin{verbatim}
## MSE :  1.685225 
##  MAPE :  3.36833
\end{verbatim}

1/2/3. Prévisions \& performances

Nous avons produit une prévision à 12 mois avec le modèle retenu
(ARMA(12,12) subset \{AR:1,12 ; MA:12\} -- ARCH(1)) et tracé les
prévisions ponctuelles avec leurs IC à 95 \%. Les bandes couvrent
l'ensemble des observations. On obtient un critère MSE à 1,685 °C², et
un critère MAPE à 3,37 \%. 3,37 \%. Ces niveaux indiquent des erreurs de
prévision modérées pour des températures mensuelles : en moyenne,
l'écart-type de l'erreur est de l'ordre de 1,3 °C et l'erreur relative
tourne autour de 3--4 \%.

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-33-1.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-33-2.pdf}

\begin{verbatim}
## MSE :  9.151211 
##  MAPE :  5.514266
\end{verbatim}

\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-33-3.pdf}
\includegraphics{TP_Enzo_Munoz_Maxime_Guilbaud_Hugo_Munier_files/figure-latex/unnamed-chunk-33-4.pdf}

\begin{verbatim}
## MSE :  1.54128 
##  MAPE :  4.109643
\end{verbatim}

\begin{verbatim}
##              Model      MSE     MAPE
## 1 subset ARMA-ARCH 1.685225 3.368330
## 2      subset ARMA 9.151211 5.514266
## 3           SARIMA 1.541280 4.109643
\end{verbatim}

4/5. Comparer, analyser et commenter les résultats

Nous avons décidé également d'ajouter le modèle proposé par la fonction
auto.arima afin de compléter cette étude. La comparaison nous montre que
le SARIMA fournit les meilleurs prévisions car son critère MSE. Il
capture ainsi plus finement la dynamique moyenne et la saisonnalité de
la série de données. De plus, le modèle ARMA-ARCH affiche le meilleur
critère MAPE. Par ailleurs les tests ARCH non significatifs et les
faibles gains AIC/BIC nous indiquent que la dynamique de volatilité
apporte peu pour les températures puisque la variabilité est surtout
saisonière. Ainsi la qualité des prévisions dépend surtout de la
modélisation de la moyenne qui refléte la tendance lente de la série et
notamment de la forte saisonnalité annuelle qui détermine le niveau de
température mois par mois. Le modèle SARIMA se présente comme le
meilleur modèle puisqu'il minimise l'erreur en °C. Cependant dans le
cadre du TP, nous retenons le modèle ARMA subset - ARCH(1) puisqu'il
offre la meilleure précision relative et une erreur proche de celle du
modèle SARIMA. A contrario, le modèle ARMA subset ne capte pas
suffisemment la saisonnalité et ainsi dégrade ses performances
prédictives.

\end{document}
